sonar.projectKey=simple-dynamic-aws-website-demo
sonar.organization=balihb
#sonar.verbose=true
#sonar.log.level=DEBUG
sonar.qualitygate.wait=true
# renovate: datasource=docker depName=python
sonar.python.version=3.14
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.python.mypy.reportPaths=.report/mypy/output.txt
sonar.sarifReportPaths=.report/checkov/results_sarif.sarif
